### ISSUE TITLE
Error running 0002_turn_threadedcomments_into_enhancedcomments migration

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#1569]
```
otm_comments:0002_turn_threadedcomments_into_enhancedcomments
[127.0.0.1] out: Error in migration: otm_comments:0002_turn_threadedcomments_into_enhancedcomments
[127.0.0.1] out: Traceback (most recent call last):
[127.0.0.1] out:   File "manage.py", line 10, in <module>
[127.0.0.1] out:     execute_from_command_line(sys.argv)
[127.0.0.1] out:   File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
[127.0.0.1] out:     utility.execute()
[127.0.0.1] out:   File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
[127.0.0.1] out:     self.fetch_command(subcommand).run_from_argv(self.argv)
[127.0.0.1] out:   File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
[127.0.0.1] out:     self.execute(*args, **options.__dict__)
[127.0.0.1] out:   File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
[127.0.0.1] out:     output = self.handle(*args, **options)
[127.0.0.1] out:   File "/usr/local/otm/env/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 108, in handle
[127.0.0.1] out:     ignore_ghosts = ignore_ghosts,
[127.0.0.1] out:   File "/usr/local/otm/env/local/lib/python2.7/site-packages/south/migration/__init__.py", line 213, in migrate_app
[127.0.0.1] out:     success = migrator.migrate_many(target, workplan, database)
[127.0.0.1] out:   File "/usr/local/otm/env/local/lib/python2.7/site-packages/south/migration/migrators.py", line 235, in migrate_many
[127.0.0.1] out:     result = migrator.__class__.migrate_many(migrator, target, migrations, database)
[127.0.0.1] out:   File "/usr/local/otm/env/local/lib/python2.7/site-packages/south/migration/migrators.py", line 310, in migrate_many
[127.0.0.1] out:     result = self.migrate(migration, database)
[127.0.0.1] out:   File "/usr/local/otm/env/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
[127.0.0.1] out:     result = self.run(migration)
[127.0.0.1] out:   File "/usr/local/otm/env/local/lib/python2.7/site-packages/south/migration/migrators.py", line 107, in run
[127.0.0.1] out:     return self.run_migration(migration)
[127.0.0.1] out:   File "/usr/local/otm/env/local/lib/python2.7/site-packages/south/migration/migrators.py", line 81, in run_migration
[127.0.0.1] out:     migration_function()
[127.0.0.1] out:   File "/usr/local/otm/env/local/lib/python2.7/site-packages/south/migration/migrators.py", line 57, in <lambda>
[127.0.0.1] out:     return (lambda: direction(orm))
[127.0.0.1] out:   File "/usr/local/otm/app/opentreemap/otm_comments/migrations/0002_turn_threadedcomments_into_enhancedcomments.py", line 15, in forwards
[127.0.0.1] out:     mf = orm['treemap.MapFeature'].objects.get(pk=ec.object_pk)
[127.0.0.1] out:   File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
[127.0.0.1] out:     return self.get_queryset().get(*args, **kwargs)
[127.0.0.1] out:   File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 307, in get
[127.0.0.1] out:     self.model._meta.object_name)
[127.0.0.1] out: treemap.models.DoesNotExist: MapFeature matching query does not exist.

**Comment by maurizi** [comment]
Since we have switched to Django migrations this won't be popping up again.
