### ISSUE TITLE
Release: Cannot register for new account

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#2162]
I can complete the registration form at /accounts/register/ on the release branch but get the error page when I click "create account."

**Comment by maurizi** [comment]
Relevant log output:
```
015-07-20 12:54:53,475 [ERROR] django.request: Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/otm/app/opentreemap/registration_backend/views.py", line 84, in dispatch
    request, *args, **kwargs)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/registration/views.py", line 91, in dispatch
    return super(RegistrationView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/registration/views.py", line 46, in post
    return self.form_valid(request, form)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/registration/views.py", line 94, in form_valid
    new_user = self.register(request, form)
  File "/usr/local/otm/app/opentreemap/registration_backend/views.py", line 138, in register
    email=email, password=password)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/registration/models.py", line 91, in create_inactive_user
    new_user.save()
  File "/usr/local/otm/app/opentreemap/treemap/models.py", line 411, in save
    self.save_with_user(system_user, *args, **kwargs)
  File "/usr/local/otm/app/opentreemap/treemap/models.py", line 407, in save_with_user
    super(User, self).save_with_user(user, *args, **kwargs)
  File "/usr/local/otm/app/opentreemap/treemap/audit.py", line 940, in save_with_user
    super(Auditable, self).save_with_user(user, *args, **kwargs)
  File "/usr/local/otm/app/opentreemap/treemap/audit.py", line 536, in save_with_user
    models.Model.save(self, *args, **kwargs)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
IntegrityError: null value in column "last_login" violates not-null constraint
```
