### ISSUE TITLE
Crash on user profile page

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/otm-core#2366]
Seems to be caused by certain edits having data is no longer valid.

Stacktrace:
```
Internal Server Error: /users/jmorrison/
Traceback (most recent call last):
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django_tinsel/decorators.py", line 33, in routed
    return req_method(request, *args2, **kwargs2)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django_tinsel/decorators.py", line 87, in wrapper
    RequestContext(request), **kwargs)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 159, in render
    return template.render(context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/base.py", line 211, in render
    return self._render(context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/debug.py", line 89, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/base.py", line 647, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/base.py", line 787, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/template/base.py", line 825, in _resolve_lookup
    current = getattr(current, bit)
  File "/usr/local/otm/app/opentreemap/treemap/audit.py", line 1349, in current_display_value
    return self._unit_format(self.clean_current_value)
  File "/usr/local/otm/app/opentreemap/treemap/audit.py", line 1341, in clean_current_value
    return self._deserialize_value(self.current_value)
  File "/usr/local/otm/app/opentreemap/treemap/audit.py", line 1277, in _deserialize_value
    return udf_def.clean_value(value, datatype)
  File "/usr/local/otm/app/opentreemap/treemap/udf.py", line 799, in clean_value
    map(_validate, values)
  File "/usr/local/otm/app/opentreemap/treemap/udf.py", line 790, in _validate
    'allowed': ', '.join(datatype_dict['choices'])})
ValidationError: [u'Invalid choice (Kinnikinnick). Expecting Switchgrass - Panicum virgatum, Salal, kinnikinnick, Oregon grape, Dwarf arctic blue willow, lavendar, Sedge']
```

**Comment by steventlamb** [comment]
this could be a case sensitivity issue. Note that this choice exists with a different case.
