### ISSUE TITLE
Investigate UI test failures with Firefox 43 and selenium 2.46.0

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2397]
```
$ vagrant ssh app -c 'cd /opt/app/core/opentreemap && envdir /etc/otm.d/env ./manage.py test -p '\''ui*.py'\'' --noinput'
EEEEEEEEEEEEEEE
======================================================================
ERROR: test_add_trees_and_continue_to_edit (treemap.tests.ui.uitest_map.MapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 214, in setUp
    super(TreemapUITestCase, self).setUp()
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 78, in setUp
    self.use_xvfb()
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 68, in use_xvfb
    self.driver = WebDriver()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 64, in __init__
    self.binary, timeout),
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 70, in launch_browser
    self._wait_until_connectable()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 105, in _wait_until_connectable
    raise WebDriverException("Can't load the profile. Profile "
WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details.


======================================================================
ERROR: test_add_trees_with_diff_details_to_map (treemap.tests.ui.uitest_map.MapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 214, in setUp
    super(TreemapUITestCase, self).setUp()
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 78, in setUp
    self.use_xvfb()
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 68, in use_xvfb
    self.driver = WebDriver()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 64, in __init__
    self.binary, timeout),
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 70, in launch_browser
    self._wait_until_connectable()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 105, in _wait_until_connectable
    raise WebDriverException("Can't load the profile. Profile "
WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details.


======================================================================
ERROR: test_add_trees_with_same_details_to_map (treemap.tests.ui.uitest_map.MapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 214, in setUp
    super(TreemapUITestCase, self).setUp()
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 78, in setUp
    self.use_xvfb()
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 68, in use_xvfb
    self.driver = WebDriver()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 64, in __init__
    self.binary, timeout),
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 70, in launch_browser
    self._wait_until_connectable()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 105, in _wait_until_connectable
    raise WebDriverException("Can't load the profile. Profile "
WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details.


======================================================================
ERROR: test_edit_trees_on_map (treemap.tests.ui.uitest_map.MapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 214, in setUp
    super(TreemapUITestCase, self).setUp()
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 78, in setUp
    self.use_xvfb()
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 68, in use_xvfb
    self.driver = WebDriver()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 64, in __init__
    self.binary, timeout),
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 70, in launch_browser
    self._wait_until_connectable()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 105, in _wait_until_connectable
    raise WebDriverException("Can't load the profile. Profile "
WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details.


======================================================================
ERROR: test_simple_add_plot_to_map (treemap.tests.ui.uitest_map.MapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 214, in setUp
    super(TreemapUITestCase, self).setUp()
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 78, in setUp
    self.use_xvfb()
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 68, in use_xvfb
    self.driver = WebDriver()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 64, in __init__
    self.binary, timeout),
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 70, in launch_browser
    self._wait_until_connectable()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 105, in _wait_until_connectable
    raise WebDriverException("Can't load the profile. Profile "
WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details.


======================================================================
ERROR: test_simple_add_tree_to_map (treemap.tests.ui.uitest_map.MapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 214, in setUp
    super(TreemapUITestCase, self).setUp()
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 78, in setUp
    self.use_xvfb()
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 68, in use_xvfb
    self.driver = WebDriver()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 64, in __init__
    self.binary, timeout),
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 70, in launch_browser
    self._wait_until_connectable()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 105, in _wait_until_connectable
    raise WebDriverException("Can't load the profile. Profile "
WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details.


======================================================================
ERROR: setUpClass (treemap.tests.ui.uitest_map.ModeChangeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/test/testcases.py", line 1269, in setUpClass
    raise cls.server_thread.error
error: [Errno 98] Address already in use

======================================================================
ERROR: setUpClass (treemap.tests.ui.uitest_registration_views.ForgotUsernameTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/test/testcases.py", line 1269, in setUpClass
    raise cls.server_thread.error
error: [Errno 98] Address already in use

======================================================================
ERROR: setUpClass (treemap.tests.ui.uitest_registration_views.LoginLogoutTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/test/testcases.py", line 1269, in setUpClass
    raise cls.server_thread.error
error: [Errno 98] Address already in use

======================================================================
ERROR: setUpClass (treemap.tests.ui.plot_detail.uitest_delete.PlotDeleteTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/test/testcases.py", line 1269, in setUpClass
    raise cls.server_thread.error
error: [Errno 98] Address already in use

======================================================================
ERROR: setUpClass (treemap.tests.ui.plot_detail.uitest_delete.PlotEditDeleteTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/test/testcases.py", line 1269, in setUpClass
    raise cls.server_thread.error
error: [Errno 98] Address already in use

======================================================================
ERROR: setUpClass (treemap.tests.ui.plot_detail.uitest_edit.PlotEditTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/test/testcases.py", line 1269, in setUpClass
    raise cls.server_thread.error
error: [Errno 98] Address already in use

======================================================================
ERROR: setUpClass (treemap.tests.ui.plot_detail.uitest_add.PlotAddTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/test/testcases.py", line 1269, in setUpClass
    raise cls.server_thread.error
error: [Errno 98] Address already in use

======================================================================
ERROR: setUpClass (otm_comments.uitests.CommentReviewUITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/test/testcases.py", line 1269, in setUpClass
    raise cls.server_thread.error
error: [Errno 98] Address already in use

======================================================================
ERROR: setUpClass (otm_comments.uitests.CommentUITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/test/testcases.py", line 1269, in setUpClass
    raise cls.server_thread.error
error: [Errno 98] Address already in use

----------------------------------------------------------------------
Ran 6 tests in 339.518s

FAILED (errors=15)

**Comment by jwalgran** [comment]
Upgrading to the latest selenium resolves the profile errors, but still results in failing tests

```
vagrant@app:/opt/app/core/opentreemap$ VAGRANT_ENV=TEST envdir /etc/otm.d/env  ./manage.py test -p 'ui*.py' --noinput
Creating test database for alias 'default'...
Installed 16 object(s) from 1 fixture(s)
Installed 5 object(s) from 1 fixture(s)
Installed 18 object(s) from 1 fixture(s)
.- Broken pipe from ('127.0.0.1', 49986)
..- Broken pipe from ('127.0.0.1', 50197)
...EEE- Broken pipe from ('127.0.0.1', 51042)
.F.sFE...E.............
======================================================================
ERROR: test_add_tree_cancel_cleans_up_form (treemap.tests.ui.plot_detail.uitest_add.PlotAddTest)
Addresses #1716 on github
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/ui/plot_detail/uitest_add.py", line 44, in test_add_tree_cancel_cleans_up_form
    self.find('input[name="tree.height"]').send_keys('11')
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 328, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': typing})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 454, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
ElementNotVisibleException: Message: Element is not currently visible and so may not be interacted with
Stacktrace:
    at fxdriver.preconditions.visible (file:///tmp/tmplGO6X1/extensions/fxdriver@googlecode.com/components/command-processor.js:9981)
    at DelayedCommand.prototype.checkPreconditions_ (file:///tmp/tmplGO6X1/extensions/fxdriver@googlecode.com/components/command-processor.js:12517)
    at DelayedCommand.prototype.executeInternal_/h (file:///tmp/tmplGO6X1/extensions/fxdriver@googlecode.com/components/command-processor.js:12534)
    at fxdriver.Timer.prototype.setTimeout/<.notify (file:///tmp/tmplGO6X1/extensions/fxdriver@googlecode.com/components/command-processor.js:621)

======================================================================
ERROR: test_add_tree_cleans_up_header (treemap.tests.ui.plot_detail.uitest_add.PlotAddTest)
Addresses #1715 on github
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/ui/plot_detail/uitest_add.py", line 69, in test_add_tree_cleans_up_header
    self.find('input[name="tree.height"]').send_keys('11')
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 328, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': typing})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 454, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
ElementNotVisibleException: Message: Element is not currently visible and so may not be interacted with
Stacktrace:
    at fxdriver.preconditions.visible (file:///tmp/tmpPtSDLf/extensions/fxdriver@googlecode.com/components/command-processor.js:9981)
    at DelayedCommand.prototype.checkPreconditions_ (file:///tmp/tmpPtSDLf/extensions/fxdriver@googlecode.com/components/command-processor.js:12517)
    at DelayedCommand.prototype.executeInternal_/h (file:///tmp/tmpPtSDLf/extensions/fxdriver@googlecode.com/components/command-processor.js:12534)
    at fxdriver.Timer.prototype.setTimeout/<.notify (file:///tmp/tmpPtSDLf/extensions/fxdriver@googlecode.com/components/command-processor.js:621)

======================================================================
ERROR: test_add_tree_cleans_up_tree_section (treemap.tests.ui.plot_detail.uitest_add.PlotAddTest)
Addresses #1717 on github
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/ui/plot_detail/uitest_add.py", line 26, in test_add_tree_cleans_up_tree_section
    self.wait_until_visible(self.edit_plot)
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 172, in wait_until_visible
    lambda driver: element.is_displayed())
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message:


======================================================================
ERROR: test_add_tree_then_delete (treemap.tests.ui.plot_detail.uitest_delete.PlotEditDeleteTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/ui/plot_detail/uitest_delete.py", line 19, in test_add_tree_then_delete
    self.diameter_input.clear()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 83, in clear
    self._execute(Command.CLEAR_ELEMENT)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 454, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
ElementNotVisibleException: Message: Element is not currently visible and so may not be interacted with
Stacktrace:
    at fxdriver.preconditions.visible (file:///tmp/tmpMP2ZML/extensions/fxdriver@googlecode.com/components/command-processor.js:9981)
    at DelayedCommand.prototype.checkPreconditions_ (file:///tmp/tmpMP2ZML/extensions/fxdriver@googlecode.com/components/command-processor.js:12517)
    at DelayedCommand.prototype.executeInternal_/h (file:///tmp/tmpMP2ZML/extensions/fxdriver@googlecode.com/components/command-processor.js:12534)
    at fxdriver.Timer.prototype.setTimeout/<.notify (file:///tmp/tmpMP2ZML/extensions/fxdriver@googlecode.com/components/command-processor.js:621)

======================================================================
ERROR: test_tree_add_cancel (treemap.tests.ui.plot_detail.uitest_edit.PlotEditTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/ui/plot_detail/uitest_edit.py", line 61, in test_tree_add_cancel
    self.wait_until_visible(self.edit_plot)
  File "/opt/app/core/opentreemap/treemap/tests/ui/__init__.py", line 172, in wait_until_visible
    lambda driver: element.is_displayed())
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message:


======================================================================
FAIL: test_delete_plot (treemap.tests.ui.plot_detail.uitest_delete.PlotDeleteTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/ui/plot_detail/uitest_delete.py", line 39, in test_delete_plot
    self._execute_delete_workflow((1, 0), (0, 0))
  File "/opt/app/core/opentreemap/treemap/tests/ui/plot_detail/cases.py", line 60, in _execute_delete_workflow
    self._assertCantClickDeleteOrCancel()
  File "/opt/app/core/opentreemap/treemap/tests/ui/plot_detail/cases.py", line 43, in _assertCantClickDeleteOrCancel
    self.delete_cancel.click()
AssertionError: ElementNotVisibleException not raised

======================================================================
FAIL: test_delete_tree_then_plot (treemap.tests.ui.plot_detail.uitest_delete.PlotDeleteTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/ui/plot_detail/uitest_delete.py", line 46, in test_delete_tree_then_plot
    self._execute_delete_workflow((1, 0), (0, 0))
  File "/opt/app/core/opentreemap/treemap/tests/ui/plot_detail/cases.py", line 60, in _execute_delete_workflow
    self._assertCantClickDeleteOrCancel()
  File "/opt/app/core/opentreemap/treemap/tests/ui/plot_detail/cases.py", line 43, in _assertCantClickDeleteOrCancel
    self.delete_cancel.click()
AssertionError: ElementNotVisibleException not raised

----------------------------------------------------------------------
Ran 32 tests in 1029.758s

FAILED (failures=2, errors=5, skipped=1)
```
