### ISSUE TITLE
Illegal searches possible that crash results

### ISSUE THREAD

**Issue by steventlamb** [OpenTreeMap/otm-core#2420]
With the inclusion of "missing data" searches, it is possible to search for a field value but also search for mapfeatures that are missing a value for that field. This produces a mixture of a `LIKE` and `ISNULL` search, which is disallowed on the server and tiler and leads to a crash without feedback.

To fix, we should either:
1) Allow `ISNULL` and `LIKE`. Why not? Just because it doesn't make sense doesn't mean it should be illegal. (easy)
2) Add search validation to the client to prevent submitting this earch (hard)

At a glance (1) works with a simple change to the config, but we should investigate if there is a regression and/or a reason that this was not supported in the first place.

Exceptions:

appserver:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/app/core/opentreemap/treemap/decorators.py", line 45, in wrapper
    return view_fn(request, instance, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 158, in inner
    response = func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 79, in wrapper
    params = callable_or_dict(request, *args, **wrapper_kwargs)
  File "/opt/app/core/opentreemap/treemap/views/tree.py", line 67, in search_tree_benefits
    total_plots = get_cached_plot_count(filter)
  File "/opt/app/core/opentreemap/treemap/ecocache.py", line 35, in get_cached_plot_count
    return _get_or_compute(prefix, filter, compute_value)
  File "/opt/app/core/opentreemap/treemap/ecocache.py", line 45, in _get_or_compute
    value = compute_value()
  File "/opt/app/core/opentreemap/treemap/ecocache.py", line 33, in <lambda>
    compute_value = lambda: filter.get_object_count(Plot)
  File "/opt/app/core/opentreemap/treemap/search.py", line 81, in get_object_count
    return self.get_objects(ModelClass).count()
  File "/opt/app/core/opentreemap/treemap/search.py", line 65, in get_objects
    q = create_filter(self.instance, self.filterstr, DEFAULT_MAPPING)
  File "/opt/app/core/opentreemap/treemap/search.py", line 161, in create_filter
    q = _parse_filter(query, mapping)
  File "/opt/app/core/opentreemap/treemap/search.py", line 173, in _parse_filter
    return _parse_predicate(query, mapping)
  File "/opt/app/core/opentreemap/treemap/search.py", line 181, in _parse_predicate
    for kv in query.iteritems()]
  File "/opt/app/core/opentreemap/treemap/search.py", line 436, in _parse_predicate_pair
    in _parse_dict_value(value).iteritems()}
  File "/opt/app/core/opentreemap/treemap/search.py", line 402, in _parse_dict_value_for_mapping
    (valuesdict.keys(), valuesdict))
ParseException: Cannot use these keys together: [u'ISNULL', u'LIKE'] in {u'ISNULL': True, u'LIKE': u'"Daylily - Hemerocallis"'}
```

tiler:
```
[TILE RENDER ERROR] -- 400: Error: A predicate with keys ISNULL,LIKE is not valid because the predicate key ISNULL can only be combined with the following keys: 
```

**Comment by dboyer** [comment]
I thought we handled conflicting searches. Can this be closed?

**Comment by maurizi** [comment]
No, this is still an issue, we still allow detail searches at the same time as missing searches.

**Comment by jmorrison1847** [comment]
I've never heard this bug reported by a user before--I would pin it as the lowest priority.

**Comment by RickMohr** [comment]
We do see it showing up in rollbar, suggesting that users are in fact trying this kind of search.
