### ISSUE TITLE
Collection UDF tests are intermittently failing

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/otm-core#2514]
I've noticed this several times and it seems to only happen on occasion, but it's always the same 2 tests.
```

======================================================================
FAIL: test_can_delete_choice_option (treemap.tests.test_udfs.CollectionUDFTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/test_udfs.py", line 1040, in test_can_delete_choice_option
    self.assertEqual(plot.udfs['Stewardship'][0]['action'], '')
AssertionError: 'prune' != u''

======================================================================
FAIL: test_can_update_choice_option (treemap.tests.test_udfs.CollectionUDFTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/test_udfs.py", line 1015, in test_can_update_choice_option
    self.assertEqual(plot.udfs['Stewardship'][0]['action'], 'h2o')
AssertionError: 'prune' != u'h2o'

----------------------------------------------------------------------
```

**Comment by maurizi** [comment]
Duplicate of #2700
