### ISSUE TITLE
Exception when creating plot without supplying a location

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#2553]
View details in Rollbar: [https://rollbar.com/Azavea/OpenTreeMap/items/1004/](https://rollbar.com/Azavea/OpenTreeMap/items/1004/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/app/core/opentreemap/api/decorators.py", line 107, in wrapperf
    return view_f(request, *args, **kwargs)
  File "/opt/app/core/opentreemap/api/decorators.py", line 151, in wrapper
    return view_f(request, *args, **kwargs)
  File "/opt/app/core/opentreemap/treemap/decorators.py", line 45, in wrapper
    return view_fn(request, instance, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 125, in newreq
    outp = req_function(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 106, in newreq
    outp = req_function(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 33, in routed
    return req_method(request, *args2, **kwargs2)
  File "/opt/app/core/opentreemap/api/decorators.py", line 122, in wrapperf
    return view_f(request, *args, **kwargs)
  File "/opt/app/core/opentreemap/treemap/decorators.py", line 193, in wrapper
    return view_fn(request, instance, *args, **kwargs)
  File "/opt/app/core/opentreemap/api/plots.py", line 30, in wrapper
    plot_dict = plot_update_fn(request, *args, **kwargs)
  File "/opt/app/core/opentreemap/api/plots.py", line 109, in update_or_create_plot
    plot, __ = update_map_feature(data, request.user, plot)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/app/core/opentreemap/treemap/views/map_feature.py", line 281, in update_map_feature
    errors.update(save_and_return_errors(feature, user))
  File "/opt/app/core/opentreemap/treemap/views/map_feature.py", line 222, in save_and_return_errors
    thing.convert_to_database_units()
  File "/opt/app/core/opentreemap/treemap/units.py", line 65, in convert_to_database_units
    self.clean()
  File "/opt/app/core/opentreemap/treemap/models.py", line 619, in clean
    if not self.instance.bounds.geom.contains(self.geom):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/gis/geos/geometry.py", line 287, in contains
    return capi.geos_contains(self.ptr, other.ptr)
AttributeError: 'NoneType' object has no attribute 'ptr'
```

**Comment by RickMohr** [comment]
Addressed by #2554
