### ISSUE TITLE
treemap.tests.test_udfs is unreliable

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-core#2700]
After pushing a PR, jenkins failed with the complaints below. Rerunning it with @ azavea-bot reload resulted in success. Nothing in the PR has anything to do with UDFs AFAIK.

```
======================================================================
FAIL: test_can_delete_choice_option (treemap.tests.test_udfs.CollectionUDFTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/test_udfs.py", line 1040, in
test_can_delete_choice_option
    self.assertEqual(plot.udfs['Stewardship'][0]['action'], '')
AssertionError: 'prune' != u''

======================================================================
FAIL: test_can_update_choice_option (treemap.tests.test_udfs.CollectionUDFTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/test_udfs.py", line 1015, in
test_can_update_choice_option
    self.assertEqual(plot.udfs['Stewardship'][0]['action'], 'h2o')
AssertionError: 'prune' != u'h2o'
```

**Comment by RobinIsTheBird** [comment]
Note that 3 tests in this test module are now being skipped.
