### ISSUE TITLE
treemap/tests/test_udfs relies on indeterminate ordering

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-core#2716]
In http://civicci01.internal.azavea.com/view/otm/job/otm-develop/362/console, we see that two tests fail:

FAIL: test_can_delete_choice_option (treemap.tests.test_udfs.CollectionUDFTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/test_udfs.py", line 1040, in test_can_delete_choice_option
    self.assertEqual(plot.udfs['Stewardship'][0]['action'], '')
AssertionError: 'prune' != u''

======================================================================
FAIL: test_can_update_choice_option (treemap.tests.test_udfs.CollectionUDFTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/treemap/tests/test_udfs.py", line 1015, in test_can_update_choice_option
    self.assertEqual(plot.udfs['Stewardship'][0]['action'], 'h2o')
AssertionError: 'prune' != u'h2o'

This test has never failed on my local machine, didn't fail on Jenkins before the relevant PR was merged. I expect it's depending on UDFDictionary iteration order, which I expect is not guaranteed. Can probably be fixed by iterating instead of indexing by [0].

**Comment by RobinIsTheBird** [comment]
Duplicates 2700
