### ISSUE TITLE
TypeError when validating tree import multichoice field value

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#3096]
https://rollbar.com/Azavea/OpenTreeMap/items/2377/

```
Traceback (most recent call last):
 File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
   R = retval = fun(*args, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
   return self.run(*args, **kwargs)
 File "/opt/app/core/opentreemap/importer/tasks.py", line 138, in _validate_rows
   row.validate_row()
 File "/opt/app/core/opentreemap/importer/models/trees.py", line 439, in validate_row
   self.validate_user_defined_fields()
 File "/opt/app/core/opentreemap/importer/models/trees.py", line 416, in validate_user_defined_fields
   udf_def.clean_value(value)
 File "/opt/app/core/opentreemap/treemap/udf.py", line 880, in clean_value
   map(_validate, values)
TypeError: argument 2 to map() must support iteration
```

<img width="647" alt="screen shot 2017-04-07 at 8 14 41 am" src="https://cloud.githubusercontent.com/assets/17363/24806662/672090b0-1b6a-11e7-9854-5c1cf458bb99.png">

**Comment by jwalgran** [comment]
The problem appears to be caused by the fact that `json.loads` returns an integer when passed `"0"`, and we expect it to return a string.

```
In [1]: import json

In [2]: json.loads("0")
Out[2]: 0

In [3]: type(Out[2])
Out[3]: int
```
